[package]
edition = "2024"
name = "server"
version = "0.1.0"

[dependencies]
api-key = { path = "../api-key", features = ["serde"] }
axum = { workspace = true, features = ["macros"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
bincode = { version = "2", features = ["serde"] }
bmp-encoder = { path = "../bmp-encoder" }
bytes = "1.11.0"
chrono = { workspace = true, features = ["serde"] }
embedded-graphics = "0.8.1"
image = "0.25"
macaddr = { version = "1", features = ["serde"] }
mousefood = "0.2.1"
num-complex = "0.4"
ratatui = "0.29.0"
redb = "3"
reqwest = "0.12"
semver = { version = "1", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { version = "0.6", features = ["trace", "fs", "set-header"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
typed-bytes = { path = "../typed-bytes", features = ["tracing"] }
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v7"] }
